### ISSUE TITLE
Multiple sources path in config.

### ISSUE THREAD

**Issue by kraikov** [PaulRBerg/solidity-template#11]
Is there a way to provide multiple folders for compilation? My goal is to have contracts for testing purposes only and I don't want to put them inside the "**contracts**" folder.
Originally I wanted to put them inside the test folder, but I couldn't find a way to provide that in the config.

Something like this:
![image](https://user-images.githubusercontent.com/7030722/99977601-893cfe00-2dad-11eb-8c6f-ae081f0ad47b.png)

Or is there any other way I can achieve something similar?

**Comment by PaulRBerg** [comment]
Hey @kraikov, I don't think this is possible with Hardhat. Looking at their [documentation][1], the `sources` field seems to be a single directory where all contracts are stored. What I do in my [projects][2] is to create a subfolder named "test" within the "contracts" folder.

At any rate, I would re-ask this question in the [Hardhat Discord][3]. They may be able to implement this feature at some point.

[1]: https://hardhat.org/config/#path-configuration
[2]: https://github.com/paulrberg/contracts
[3]: https://hardhat.org/discord
