### ISSUE TITLE
Some Chai matchers won't work properly if ethers version is updated manually

### ISSUE THREAD

**Issue by Janther** [paulrberg/solidity-template#111]
A bit obscure but `ethers` version must match `@ethereum-waffle/chai`'s dependency for `ethers`.
Otherwise some matchers won't work properly.

In my project I update to version `5.6.6` and `yarn` kept `@ethereum-waffle/chai` using `5.6.2` even though `5.6.6` also satisfied the `^5.5.2` dependency of `@ethereum-waffle/chai`.

not a big problem but might include a caveat somewhere so people don't get lost?

**Comment by paulrberg** [comment]
Interesting! Thanks for reporting. [I just added a caveat in the README](https://github.com/paulrberg/solidity-template/commit/ff050aa4c9ae788b822c688ba3b2aeeeb12d1e82) for this.

I think that this problem will go away once I switch this template to use [Hardhat's chai matchers](https://github.com/paulrberg/solidity-template/issues/112).

**Comment by paulrberg** [comment]
Closing this issue as completed since the recent migration to use Hardhat Toolbox in #120.
