### ISSUE TITLE
Switch to using Hardhat Chai matchers instead of Waffle

### ISSUE THREAD

**Issue by paulrberg** [paulrberg/solidity-template#112]
See [Hardhat Chain Matchers](https://www.notion.so/nomiclabs/Public-Hardhat-Chai-Matchers-11feb9185dd54591999f4e813f90c10c) on Notion.

**Comment by Thomasrichard1122** [comment]
> See [Hardhat Chain Matchers](https://www.notion.so/nomiclabs/Public-Hardhat-Chai-Matchers-11feb9185dd54591999f4e813f90c10c) on Notion.
