### ISSUE TITLE
yarn build not existent in "script"

### ISSUE THREAD

**Issue by feulf** [paulrberg/solidity-template#21]
I think `yarn compile` does what this is saying:
https://github.com/paulrberg/solidity-template/blob/main/README.md#typechain

Please check and update the README or package.json.

Thanks!

p.s. Great work with this template repo!

**Comment by paulrberg** [comment]
Hey Federico, thanks for reporting this!

Fixed in [c61c929](https://github.com/paulrberg/solidity-template/commit/c61c92913f932d2fee47197c3bc1727e7215b8e6).
