### ISSUE TITLE
Property 'waffle' does not exist on type 'HardhatRuntimeEnvironment'

### ISSUE THREAD

**Issue by SvenMeyer** [paulrberg/solidity-template#23]
If I (manually) changed my project which is based on this template, and tried to import `hre`

```typescript
import hre from "hardhat";
...
const { deployContract } = hre.waffle;
...
signers = await hre.ethers.getSigners();
```

I get the error message(s)
`Property 'waffle' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)`
`Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)`

The error disappear if I have these lines of code
```typescript
import hre from "hardhat";

import "@nomiclabs/hardhat-waffle";
import "@nomiclabs/hardhat-ethers";
```

`Am I missing something ?

**Comment by paulrberg** [comment]
Whoops! I thing one of my latest commits introduced a bug. Let me check.

**Comment by paulrberg** [comment]
Actually, no. There is no issue in the template.

The reason you need those imports is because that's how Hardhat polyfills the runtime environment with the `ethers` and `waffle` objects. You can read more about how plugins work [here](https://hardhat.org/guides/project-setup.html#plugins-and-dependencies).

**Comment by SvenMeyer** [comment]
Thanks for looking into it.

I based my project on your template (mid December) , had all the hardhat imports, but even when copying (back) your Greeter files, it would still would complain Property `'ethers' does not exist on type 'HardhatRuntimeEnvironment'`
... and within the scripts
`Module '"../node_modules/hardhat/internal/lib/hardhat-lib"' has no exported member 'ethers'.`

Now I started with a fresh template and copied my code into it, now it looks all good.
If you happen to have an idea what might have changed and what I might have messed up , then let me know.

**Comment by paulrberg** [comment]
Yes, because Hardhat has [path configuration](https://hardhat.org/config/#path-configuration). You may also want to ensure that the `test_temp` is included in your `tsconfig.json` file.

**Comment by SvenMeyer** [comment]
Sorry to bother you again ... As before I created a fresh project from your project, looks all good.
Now looked at the `scripts/deploy.js` in my project (almost fresh setup using your setup), now VSC complains (again, with a red underline of 'ethers') ... however , it all executes fine without errors

`import { ethers } from "hardhat";`

```
import ethers
Module '"../node_modules/hardhat/internal/lib/hardhat-lib"' has no exported member 'ethers'.ts(2305)
```

if I change the code to
```
import hre from "hardhat";
const Greeter: ContractFactory = await hre.ethers.getContractFactory("Greeter");
```
I get
`Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)`



(Apparently I am (not yet) neither a hardhat nor Typescript expert, but ...) I barely made any changes , how come I get these errors (again) ?

**Comment by paulrberg** [comment]
> now VSC complains .. however, it all executes fine without errors

You're most likely using the global TypeScript installed by VSCode by default. You should be using the local version, which handles the Hardhat types correctly. Refer to this post on StackOverflow for how to do this:

[What TypeScript version is Visual Studio Code using? How to update it?](https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it)
