### ISSUE TITLE
Migrate to @typechain/hardhat

### ISSUE THREAD

**Issue by TomAFrench** [paulrberg/solidity-template#27]
The `hardhat-typechain` package is now being maintained officially as [`@typechain/hardhat`](https://github.com/ethereum-ts/TypeChain/tree/master/packages/hardhat).

**Comment by paulrberg** [comment]
I was actually wondering why I am getting "peer dependency" warnings. Thanks for the heads-up, dude!

**Comment by paulrberg** [comment]
Implemented in [c243ee6](https://github.com/paulrberg/solidity-template/commit/c243ee6774e59ee2de1dfe8e1ebe1e3feab002ed).
