### ISSUE TITLE
Use Solidity ver. ^0.8.4 in Greeter.sol

### ISSUE THREAD

**Issue by scorpion9979** [paulrberg/solidity-template#44]
Greeter.sol has a descriptive `GreeterError` structured error defined. Structured errors were only introduced in 0.8.4, and compiling for any solidity version prior to 0.8.4 would produce a `ParserError` compile error.

**Comment by paulrberg** [comment]
Great catch! Fixed in [2625524](https://github.com/paulrberg/solidity-template/commit/2625524b96b3d53d51766cea260dba93f7b1e255).
