### ISSUE TITLE
Guide missing 

### ISSUE THREAD

**Issue by aj07** [PaulRBerg/solidity-template#5]
While running "yarn compile" it throws error as "Error: Please set your MNEMONIC in a .env file "  

This is known issue. But for a newbie would be great if put there how do set up or link the relevant doc around it

**Comment by PaulRBerg** [comment]
Hi @aj07, thanks for your feedback. I tried to be as descriptive as possible with the message, but there's so much I can do on my own. A search for "Ethereum mnemonic" on Google clarifies what the value of MNEMONIC should be.

How would you make the error message better?

**Comment by PaulRBerg** [comment]
I will close this because of lack of activity.
